# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hellman_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Hellman_Window(object):
    def setupUi(self, Hellman_Window):
        Hellman_Window.setObjectName("Hellman_Window")
        Hellman_Window.resize(800, 500)
        self.centralwidget = QtWidgets.QWidget(Hellman_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.encrypt.setGeometry(QtCore.QRect(680, 170, 101, 51))
        self.encrypt.setObjectName("encrypt")
        self.decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.decrypt.setGeometry(QtCore.QRect(680, 320, 101, 51))
        self.decrypt.setObjectName("decrypt")
        self.enter_key_a = QtWidgets.QLineEdit(self.centralwidget)
        self.enter_key_a.setGeometry(QtCore.QRect(350, 10, 160, 20))
        self.enter_key_a.setInputMask("")
        self.enter_key_a.setObjectName("enter_key_a")
        self.enter_key_b = QtWidgets.QLineEdit(self.centralwidget)
        self.enter_key_b.setGeometry(QtCore.QRect(350, 40, 160, 20))
        self.enter_key_b.setInputMask("")
        self.enter_key_b.setObjectName("enter_key_b")
        self.enter_primitive = QtWidgets.QLineEdit(self.centralwidget)
        self.enter_primitive.setGeometry(QtCore.QRect(20, 40, 171, 20))
        self.enter_primitive.setInputMask("")
        self.enter_primitive.setObjectName("enter_primitive")
        self.output_text = QtWidgets.QTextEdit(self.centralwidget)
        self.output_text.setGeometry(QtCore.QRect(350, 170, 300, 200))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.output_text.setFont(font)
        self.output_text.setReadOnly(True)
        self.output_text.setObjectName("output_text")
        self.to_rsa = QtWidgets.QPushButton(self.centralwidget)
        self.to_rsa.setGeometry(QtCore.QRect(180, 440, 140, 50))
        self.to_rsa.setObjectName("to_rsa")
        self.input_text = QtWidgets.QTextEdit(self.centralwidget)
        self.input_text.setGeometry(QtCore.QRect(20, 170, 300, 200))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_text.setFont(font)
        self.input_text.setObjectName("input_text")
        self.enter_module = QtWidgets.QLineEdit(self.centralwidget)
        self.enter_module.setGeometry(QtCore.QRect(20, 10, 171, 20))
        self.enter_module.setInputMask("")
        self.enter_module.setObjectName("enter_module")
        self.to_gamal = QtWidgets.QPushButton(self.centralwidget)
        self.to_gamal.setEnabled(True)
        self.to_gamal.setGeometry(QtCore.QRect(350, 440, 140, 50))
        self.to_gamal.setObjectName("to_gamal")
        self.help = QtWidgets.QPushButton(self.centralwidget)
        self.help.setEnabled(False)
        self.help.setGeometry(QtCore.QRect(230, 20, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.help.setFont(font)
        self.help.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.help.setAutoFillBackground(False)
        self.help.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.help.setAutoDefault(False)
        self.help.setDefault(False)
        self.help.setFlat(True)
        self.help.setObjectName("help")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(350, 150, 191, 16))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 191, 16))
        self.label_2.setObjectName("label_2")
        Hellman_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Hellman_Window)
        QtCore.QMetaObject.connectSlotsByName(Hellman_Window)

    def retranslateUi(self, Hellman_Window):
        _translate = QtCore.QCoreApplication.translate
        Hellman_Window.setWindowTitle(_translate("Hellman_Window", "Шифрование Диффи-Хеллмана"))
        self.encrypt.setText(_translate("Hellman_Window", "Зашифровать"))
        self.decrypt.setText(_translate("Hellman_Window", "Расшифровать"))
        self.enter_key_a.setPlaceholderText(_translate("Hellman_Window", "Введите секретный ключ А"))
        self.enter_key_b.setPlaceholderText(_translate("Hellman_Window", "Введите секретный ключ В"))
        self.enter_primitive.setPlaceholderText(_translate("Hellman_Window", "Введите примитивный элемент"))
        self.to_rsa.setText(_translate("Hellman_Window", "RSA"))
        self.enter_module.setPlaceholderText(_translate("Hellman_Window", "Введите модуль криптосистемы"))
        self.to_gamal.setText(_translate("Hellman_Window", "Эль-Гамаль"))
        self.help.setText(_translate("Hellman_Window", "Помощь"))
        self.label_5.setText(_translate("Hellman_Window", "Результат"))
        self.label_2.setText(_translate("Hellman_Window", "Введите сообщение"))
