# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu_Window(object):
    def setupUi(self, Menu_Window):
        Menu_Window.setObjectName("Menu_Window")
        Menu_Window.resize(800, 500)
        self.centralwidget = QtWidgets.QWidget(Menu_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 120, 800, 80))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 240, 781, 141))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.to_rsa = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.to_rsa.setMinimumSize(QtCore.QSize(140, 80))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.to_rsa.setFont(font)
        self.to_rsa.setObjectName("to_rsa")
        self.horizontalLayout.addWidget(self.to_rsa)
        self.to_gamal = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.to_gamal.setEnabled(True)
        self.to_gamal.setMinimumSize(QtCore.QSize(140, 80))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.to_gamal.setFont(font)
        self.to_gamal.setObjectName("to_gamal")
        self.horizontalLayout.addWidget(self.to_gamal)
        self.to_hellman = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.to_hellman.setMinimumSize(QtCore.QSize(140, 80))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.to_hellman.setFont(font)
        self.to_hellman.setObjectName("to_hellman")
        self.horizontalLayout.addWidget(self.to_hellman)
        Menu_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Menu_Window)
        QtCore.QMetaObject.connectSlotsByName(Menu_Window)

    def retranslateUi(self, Menu_Window):
        _translate = QtCore.QCoreApplication.translate
        Menu_Window.setWindowTitle(_translate("Menu_Window", "Меню"))
        self.label.setText(_translate("Menu_Window", "Выберите один из предложенных типов шифрования"))
        self.to_rsa.setText(_translate("Menu_Window", "RSA"))
        self.to_gamal.setText(_translate("Menu_Window", "Эль-Гамаль"))
        self.to_hellman.setText(_translate("Menu_Window", "Диффи-Хелман"))
