# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rsa_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Rsa_Window(object):
    def setupUi(self, Rsa_Window):
        Rsa_Window.setObjectName("Rsa_Window")
        Rsa_Window.resize(800, 500)
        self.centralwidget = QtWidgets.QWidget(Rsa_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.enter_p = QtWidgets.QLineEdit(self.centralwidget)
        self.enter_p.setGeometry(QtCore.QRect(20, 10, 171, 20))
        self.enter_p.setInputMask("")
        self.enter_p.setObjectName("enter_p")
        self.enter_q = QtWidgets.QLineEdit(self.centralwidget)
        self.enter_q.setGeometry(QtCore.QRect(20, 40, 171, 20))
        self.enter_q.setInputMask("")
        self.enter_q.setText("")
        self.enter_q.setObjectName("enter_q")
        self.enter_key = QtWidgets.QLineEdit(self.centralwidget)
        self.enter_key.setGeometry(QtCore.QRect(350, 10, 160, 20))
        self.enter_key.setInputMask("")
        self.enter_key.setObjectName("enter_key")
        self.input_text = QtWidgets.QTextEdit(self.centralwidget)
        self.input_text.setGeometry(QtCore.QRect(20, 170, 300, 200))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_text.setFont(font)
        self.input_text.setObjectName("input_text")
        self.output_text = QtWidgets.QTextEdit(self.centralwidget)
        self.output_text.setGeometry(QtCore.QRect(350, 170, 300, 200))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.output_text.setFont(font)
        self.output_text.setReadOnly(True)
        self.output_text.setObjectName("output_text")
        self.encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.encrypt.setGeometry(QtCore.QRect(680, 170, 101, 51))
        self.encrypt.setObjectName("encrypt")
        self.decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.decrypt.setGeometry(QtCore.QRect(680, 320, 101, 51))
        self.decrypt.setObjectName("decrypt")
        self.to_rsa = QtWidgets.QPushButton(self.centralwidget)
        self.to_rsa.setEnabled(False)
        self.to_rsa.setGeometry(QtCore.QRect(140, 440, 140, 50))
        self.to_rsa.setObjectName("to_rsa")
        self.to_gamal = QtWidgets.QPushButton(self.centralwidget)
        self.to_gamal.setGeometry(QtCore.QRect(300, 440, 140, 50))
        self.to_gamal.setObjectName("to_gamal")
        self.to_hellman = QtWidgets.QPushButton(self.centralwidget)
        self.to_hellman.setGeometry(QtCore.QRect(460, 440, 140, 50))
        self.to_hellman.setObjectName("to_hellman")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 150, 191, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 150, 191, 16))
        self.label_2.setObjectName("label_2")
        self.help = QtWidgets.QPushButton(self.centralwidget)
        self.help.setEnabled(False)
        self.help.setGeometry(QtCore.QRect(230, 20, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.help.setFont(font)
        self.help.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.help.setAutoFillBackground(False)
        self.help.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.help.setAutoDefault(False)
        self.help.setDefault(False)
        self.help.setFlat(True)
        self.help.setObjectName("help")
        Rsa_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Rsa_Window)
        QtCore.QMetaObject.connectSlotsByName(Rsa_Window)

    def retranslateUi(self, Rsa_Window):
        _translate = QtCore.QCoreApplication.translate
        Rsa_Window.setWindowTitle(_translate("Rsa_Window", "Шифрование RSA"))
        self.enter_p.setPlaceholderText(_translate("Rsa_Window", "Введите p"))
        self.enter_q.setPlaceholderText(_translate("Rsa_Window", "Введите q"))
        self.enter_key.setPlaceholderText(_translate("Rsa_Window", "Введите ключ шифровнания"))
        self.encrypt.setText(_translate("Rsa_Window", "Зашифровать"))
        self.decrypt.setText(_translate("Rsa_Window", "Расшифровать"))
        self.to_rsa.setText(_translate("Rsa_Window", "RSA"))
        self.to_gamal.setText(_translate("Rsa_Window", "Эль-Гамаль"))
        self.to_hellman.setText(_translate("Rsa_Window", "Диффи-Хелман"))
        self.label.setText(_translate("Rsa_Window", "Введите сообщение"))
        self.label_2.setText(_translate("Rsa_Window", "Результат"))
        self.help.setText(_translate("Rsa_Window", "Помощь"))
